// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IHomeFields {
  /** Заголовок */
  title?: string | undefined;

  /** services */
  services?: Entry<{ [fieldId: string]: unknown }>[] | undefined;
}

export interface IHome extends Entry<IHomeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'home';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IStakeholderServiceFields {
  /** name */
  name?: string | undefined;

  /** price */
  price?: string | undefined;

  /** slug */
  slug?: string | undefined;
}

export interface IStakeholderService extends Entry<IStakeholderServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'stakeholder-service';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'home' | 'stakeholder-service';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
